### ISSUE TITLE
Putting elements into layout

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Otherion/RPG-Status-Window#2]
There is no need to define elements outside of the layout definition anymore.  This is the "old way" so to speak.  Can you tell me where you picked up your original code that used this older technique? I'm modifying as I find them.

The new way is to define everything in the layout and use keys to identify your output elements.

This statement should have a key added just like start_class has.
```
    cname = sg.Text('', size=(20, 1))   # The name of your character
    start_class = sg.Text('', size=(12, 1), font=('Helvetica', 20), background_color='black', text_color='white', 
                          justification='center', key='class')
```

Suggested changes include
- Copy and paste these 2 sg.Text calling into the layout.  
- Add a key to your cname sg.Text.  In the example code below I assumed key='cnamekey'.
- Change your cname.Update calls to

`form.FindElement('cnamekey', name)
`

**Comment by Otherion** [comment]
I found them when looking in the 'Cookbook'. Looking through the cookbook now (https://pysimplegui.readthedocs.io/en/latest/cookbook/), I still see many examples of defining elements outside the layout like with the stopwatch, running timer, media player, custom progress bar examples to name a few. 
I updated my code and removed the elements I had outside the layout.

**Comment by MikeTheWatchGuy** [comment]
Thank you!  I didn't realize the Cookbook was so out of date.

Went through and hit just about every Recipe.  No more externally defined elements in the Cookbook!  Updated some to include Menus too.

**Comment by MikeTheWatchGuy** [comment]
OK, Cookbook has been fixed.  No more examples like that in the online cookbook.  Now have to check the .py demo code.
